scm:
    type: git
    repository: https://github.com/keizz/line-bot-sdk-test.git
    rev: master

steps:
    - name: Some action before playbooks
      cmd: echo "do something"


playbooks:
    - name: t
      path: projects/t/playbooks/
      inventories:
          - name: t
            path: /app/flask/nci-ansible-ui-quick-setup/data/projects/t/hosts

