- name: Set MySQL with modules
  hosts: mysql
  gather_facts: no
  vars:
    MySQL_root_user: root
    MySQL_root_pass: test
    MySQL_port: 3306

  tasks:
  - name: install MySQL-python and python-simplejson
    yum:
        name: "{{ item }}"
        state: installed
    with_items:
        - MySQL-python
    tags: yum
