- name: user_test
  hosts: mysql
  vars:
   MySQL_root_user: root
   MySQL_root_pass: root

  tasks:
  - name: user_test
    mysql_user:
        name: test3
        state: present
        host: "{{ item }}"
        password: replication!$#
        priv: '*.*:REPLICATION CLIENT'
        login_user: "{{ MySQL_root_user }}"
        login_password: "{{ MySQL_root_pass }}"
        login_unix_socket: /tmp/mysql.sock
    with_items:
        - 192.168.1.67
        - 192.168.1.68
    tags: mysql_user

  - name: user_drop_test
    mysql_user:
        name: root
        host: ::1
        state: absent
#        host: "{{ item }}"
#        password: test
        priv: '*.*:ALL'
        login_user: "{{ MySQL_root_user }}"
        login_password: "{{ MySQL_root_pass }}"
        login_unix_socket: /tmp/mysql.sock
    with_items:
        - 192.168.1.67
        - 192.168.1.68
    tags: user_drop_test

